### PR TITLE
Text and List added to the Component Lib.

### PR DESCRIPTION
**Pull request by ashifkhn**
Text and List added to the Component Lib,
This isn't a responsive yet

Inspect the deploy log: https://app.netlify.com/sites/whyui/deploys/6204ad53ebc4ce000737cf3c
Browse the preview: https://deploy-preview-9--whyui.netlify.app/

### CODE REVIEW

**Review by Pratham82 — COMMENTED** [review]
good to go, just check if the grey text is actually gray, maybe you can add more lighter shade.

**Comment by ashifkhn** [comment]
> good to go, just check if the grey text is actually gray, maybe you can add more lighter shade.

Thanks. I'll do the change

**Review by sakshi006 — CHANGES_REQUESTED** [review]
text utilities looks fine.
I am not able to check the list component, i think the links are not updated. On clicking the lists from sidebar it is taking me to text utilities only.

**Comment by ashifkhn** [comment]
> text utilities looks fine. I am not able to check the list component, i think the links are not updated. On clicking the lists from sidebar it is taking me to text utilities only.

fixed

**Pull request merged**
